name: liquidarmy
static_sites:
  - name: liquidarmy
    github:
      repo: martinteoharov/liquidarmy
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: .
    environment_slug: node-js
    routes:
      - path: /
